### 6.1 Авторизация пользователя
## API_atol_online_v4.pdf стр. 12 (Версия сервиса v4 Версия документа 5.15)

# Если в течение 24 часов с момента запроса токена повторно запросить токен, то вы
# получите новый токен и время его жизни будет так же 24 часа, либо ранее полученный
# токен и время его жизни будет 24 часа от момента первого получения клиентом этого
# токена. Количество одновременно действующих токенов, которые может получить клиент
# равно количеству реплик сервиса АТОЛ Онлайн, работающих в текущий момент.
# Рекомендуется запрашивать новый токен только при получении от сервиса ошибки об
# истечении времени жизни предыдущего токена (см. ошибку ExpiredToken в разделе 8.1
# Ошибки сервиса).

POST {{host}}/getToken
Content-Type: application/json; charset=utf-8

{
    "login": "{{login}}",
    "pass": "{{password}}"
}

> {%
    client.global.set("atol-token", response.body.token);
%}

>> ./../../data/tmp/http/get-token_{{$isoTimestamp}}.json
